### ISSUE TITLE
[BUG] ##[error]unable to get local issuer certificate

### ISSUE THREAD

**Issue by tamipangadil** [hashicorp/vault-action#99]
**Describe the bug**

The action is no longer connecting to our Vault server.

**To Reproduce**

1. Add your build.yaml workflow
2. Add this step:
```
- name: Import Secrets from Vault
  id: vault_secrets
  uses: hashicorp/vault-action@master
  with:
    url: ${{ secrets.VAULT_ADDR }}
    method: github
    githubToken: ${{ secrets.VAULT_ACCESS_TOKEN }}
    kv-version: 2
    exportEnv: false
    secrets: |
      mysecret MY_SECRET;
```

Note: The vault address's SSL cert is still valid until next year

**Expected behavior**

It will then show an error: `##[error]unable to get local issuer certificate`

**Log Output**

```
##[debug]'
##[debug]Loading env
Run RichiCoder1/vault-action@master
  with:
    url: ***
    method: github
    githubToken: ***
    kv-version: 2
    exportEnv: false
    secrets: mysecret MY_SECRET;
  
    tlsSkipVerify: false
::group::Test Get Vault Secrets
Test Get Vault Secrets
  
  
  ##[debug]Retrieving Vault Token from v1/auth/github/login endpoint
  ::endgroup::
##[error]unable to get local issuer certificate
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Import Secrets from Vault
```

**Additional context**

We managed to fix it by sticking to the previous working version: `RichiCoder1/vault-action@v1.0.1` or `hashicorp/vault-action@v1.0.1` and not using `master` version

**Comment by RichiCoder1** [comment]
This error could be a lot of things unforunately, but I wonder if the addition of the `https` option object (here: https://github.com/hashicorp/vault-action/commit/b3a02289e7f4cb9d09da630133cfd6583513310c#diff-4685e9a2b21243b3b102582af40b9b06R33) could be changing behaviors, even if it's empty?

**Comment by tamipangadil** [comment]
I'm not sure with that. Should we need to provide all those details just connecting to our Vault server?

**Comment by Shailen-Patel4** [comment]
Im also getting this same error in github actions: `##[error]unable to get local issuer certificate`.

**Comment by tamipangadil** [comment]
Based on @jasonodonnell test,
```
...
caCertificate: ${{ secrets.VAULTCA }}
clientCertificate: ${{ secrets.VAULT_CLIENT_CERT }}
clientKey: ${{ secrets.VAULT_CLIENT_KEY }}
```

He added this but he never tested using `tlsSkipVerify: true`

**Comment by jasonodonnell** [comment]
It appears `dist/index.js` was not run before merging into master, so the final code changes weren't reflected there.  I've opened #100 to update the build.

Thanks for the note about missing test coverage on `tlsSkipVerify`, that is the case and I'll add coverage there.

**Comment by tamipangadil** [comment]
Great! Thanks for looking in to this issue today.

**Comment by jasonodonnell** [comment]
Master build has been updated, however, I did have a bug with `tlsSkipVerify` which is being addressed here: https://github.com/hashicorp/vault-action/pull/101.  Hopefully this resolves your issue (you could point to this commit if you want to try it I think).

**Comment by peterlogg** [comment]
Now fails with :
```bash
##[error]write EPROTO 140601684203392:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
```.

**Comment by prashant6475** [comment]
We are running into a similar kind of issue:

75::group::Get Vault Secrets
276
Get Vault Secrets


**278##[error]self signed certificate in certificate chain**
279##[debug]Node Action run completed with exit code 1
280##[debug]Finishing: Import Secrets

**Comment by jasonodonnell** [comment]
@prashant6475 This should be fixed with the latest push to master.  Did you set either:

## Recommended

Give vault-action the CA used to sign the server certificate so it can verify the authenticity of the certiciate:

```
caCertificate: ${{ secrets.VAULTCA }}
```

## Not Recommended

This is not recommended because verifying the certificate is a good thing to do.  Nonetheless, there's an option to disable verification:

```
tlsSkipVerify: true
```

**Comment by jasonodonnell** [comment]
Furthermore, we make no guarantees that `master` will always be stable.  We recommend that you pin your action to a tagged release.  Currently the TLS and UX changes are unreleased.  Thanks for testing!

**Comment by prashant6475** [comment]
Thanks suggestion on ssl worked, we have been testing against kv2 spaces, seems like we get a 404 error, but same works for kv1. 
Does this action supports kv2 spaces?

**Comment by jasonodonnell** [comment]
@prashant6475 Yes this supports most secret engines. Can you open a separate issue so we can gather more information?  This is unrelated to TLS.

**Comment by jasonodonnell** [comment]
@tamipangadil Was your original issue resolved with newer commits of `vault-action`? Looking to close this issue.

**Comment by jasonodonnell** [comment]
Closing since this seems resolved.

**Comment by tirelibirefe** [comment]
nope, the problem still exists in Dec.2022.
TLS enabled Vault doesn't work on EKS.

`http: TLS handshake error from 10.61.20.41:33356: remote error: tls: bad certificate`

**Comment by tamipangadil** [comment]
@jasonodonnell This might be outdated but we just made this work on our GitHub actions. We provided the CA cert and read the k-v on `secret/data` instead.
